### ISSUE TITLE
Font Awesome 6 Pro

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/utc-tailwind-genesis-theme#17]
To use Pro, we will need to move away from queuing a CDN version in theme, and use the plugin:
- https://wordpress.org/plugins/font-awesome/

**Comment by UTCbridget** [comment]
It's required as part of my code in onboarding.php
![Screen Shot 2022-04-06 at 2 25 02 PM](https://user-images.githubusercontent.com/82905787/162043033-929b3cf9-5961-4855-846e-3307fd70c57e.png)
:

**Comment by UTCbridget** [comment]
I make it required as part of the onboarding.php:

![Screen Shot 2022-04-06 at 2 27 24 PM](https://user-images.githubusercontent.com/82905787/162043425-a383cd5e-84a4-4a73-8048-7cb8e621a776.png)
