### ISSUE TITLE
Ongoing theming updates

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/utc-tailwind-genesis-theme#5]

**Comment by UTCGilligan** [comment]
- [ ] Add to Any styling issues
![Screen Shot 2022-04-25 at 9 05 25 AM](https://user-images.githubusercontent.com/49878588/165095160-381b93e6-b6f2-40b1-96b5-e07bdc46fdd9.png)
![Screen Shot 2022-04-25 at 9 05 46 AM](https://user-images.githubusercontent.com/49878588/165095172-4ef5048d-4b8e-4958-8374-4a6677083b20.png)

**Comment by UTCbridget** [comment]
My last commit and merge should fix this: https://github.com/UTCWeb/utc-tailwind-genesis-theme/commit/601866773fe9030a48c2e7d93bddd05cc8aeb993

**Comment by UTCGilligan** [comment]
- [ ] Social icons invisible
![Screen Shot 2022-04-27 at 11 04 24 AM](https://user-images.githubusercontent.com/49878588/165549943-d0f5fc20-153e-4b1d-9d3a-4d470ddb03b0.png)

**Comment by UTCGilligan** [comment]
- [ ] Anchor link scroll does not account for height of sticky header.

See: https://blog.utc.edu/news/yearly-archives/#year2022

**Comment by UTCbridget** [comment]
Remove feature image in the admin sidebar does not remove the feature image but replace feature image does work as it should.
