### ISSUE TITLE
Teaser text should try excerpt first, then first xxx characters of post

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/utc-tailwind-genesis-theme#57]
If the article begins with a video OEmbed, the Youtube link is visible in the teaser text.
<img width="1075" alt="Screen Shot 2022-08-25 at 5 41 43 PM" src="https://user-images.githubusercontent.com/49878588/186774373-3a6c79be-5956-4f51-809f-161694dd9119.png">

Editors are used to using the excerpt, which was used in the previous theme.

Try using `<?php the_excerpt(); >` 
- https://developer.wordpress.org/reference/functions/the_excerpt/

> Displays the [excerpt](https://codex.wordpress.org/Excerpt) of the current post after applying several filters to it including auto-p formatting which turns double line-breaks into [HTML](https://codex.wordpress.org/Glossary#HTML) paragraphs. It uses [get_the_excerpt()](https://developer.wordpress.org/reference/functions/get_the_excerpt/) to first generate a trimmed-down version of the full post content should there not be an explicit excerpt for the post.

**Comment by UTCbridget** [comment]
@UTCGilligan, there doesn't appear to be a place for the excerpt in the classic editor. Also, the video URL IS the first paragraph. May need to implement php detection.

**Comment by UTCbridget** [comment]
https://www.howtosolutions.net/2019/10/wordpress-missing-excerpt-in-page-or-post-editor/

**Comment by UTCGilligan** [comment]
### Classic Editor:
![Screen Shot 2022-08-30 at 8 04 07 AM](https://user-images.githubusercontent.com/49878588/187432080-5d8b76f5-c053-4e28-81eb-d8a595b5562c.png)
![Screen Shot 2022-08-30 at 8 04 19 AM](https://user-images.githubusercontent.com/49878588/187432103-59a74182-086b-49fb-9231-24046c2293fc.png)

**Comment by UTCbridget** [comment]
Completed.
