### ISSUE TITLE
Horizontal menu is cut off on iPhone mobile

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/utc-tailwind-genesis-theme#79]
![Screenshot 2023-09-12 at 13 20 26](https://github.com/UTCWeb/utc-tailwind-genesis-theme/assets/49878588/d4470ca9-fdc8-4472-a27f-692030b6f32b)

![Screenshot 2023-09-12 at 13 22 42](https://github.com/UTCWeb/utc-tailwind-genesis-theme/assets/49878588/1a393943-f370-48af-924f-033472718366)

**Comment by UTCGilligan** [comment]
Screenshots from my iPhone 12:
![IMG_3751](https://github.com/UTCWeb/utc-tailwind-genesis-theme/assets/49878588/4b2ef42e-c74f-457b-86d7-7deaf38475f1)
![IMG_3752](https://github.com/UTCWeb/utc-tailwind-genesis-theme/assets/49878588/e424e15b-3f8d-4b28-a628-67b156289390)

**Comment by UTCbridget** [comment]
Ugh. Ok.

**Comment by weston-gentry** [comment]
Fixed in #102
